[package]
name = "server"
version.workspace = true
edition.workspace = true

[dependencies]
agent.workspace = true
tools.workspace = true
genai.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
schemars.workspace = true
futures.workspace = true
axum.workspace = true
tokio = { workspace = true, features = ["net", "signal", "sync", "time"] }
tower-http.workspace = true
dotenvy.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
async-stream.workspace = true
tokio-util.workspace = true
telemetry.workspace = true
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
tracing-opentelemetry.workspace = true
sha2.workspace = true

[dev-dependencies]
tower.workspace = true
http-body-util.workspace = true
tokio = { workspace = true, features = ["io-util"] }

[lints]
workspace = true
